sugarcalendar/core

includes/meta-boxes.php
Page fails to reload posting new event, or updating an event with wp_debug on.  This issue fixes this.
=> Fixed misnamed variables

sugar-event-calendar/includes/admin/settings.php
This small patch allows you to use something like
`'func' => array( $this, 'license_support_output' ),` 
In the `sugar_calendar_settings_subsections` Filter. It doesn't prevent the way that Sugar Calendar Standard/Pro is handling it currently from working, but allows some flexibility for other extensions.
=> Also check is_callable() for settings sections

sugar-event-calendar/includes/themes/legacy/functions.php
This change makes targeting Past and Upcoming days on the calendar with CSS/JS easier to do. It applies to every type of Calendar output.
=> Add Past and Upcoming CSS Classes to the Calendar output

sugar-event-calendar/includes/themes/legacy/events-list.php
This adds Actions to before and after the Events List similarly to how the Calendar does.
Currently only the Widget has these actions for the Event List, but if you were to call `sc_get_events_list()` directly in your theme template files there would be no Actions before or after the Events List without this change.
=> Add Actions before and after the output of the Events List

sugar-event-calendar/includes/events/capabilities.php
This commit avoids a debug notice in Sugar Calendar when another plugin mangles the map_meta_cap filter by no longer returning an array.
Props Timi Wahalahti for reporting this to our support team.
Fixes #31.
=> Bail early if no array to get a post ID from.

sugar-event-calendar/includes/admin/list-tables/class-wp-list-table-base.php, sugar-event-calendar/includes/admin/nav.php
Omits non-public taxonomies from tabs and filters when viewing Calendar
Fixes #98
=> Hides non-public taxonomies from UI

sugar-event-calendar/includes/admin/list-tables/class-wp-list-table-base.php, sugar-event-calendar/includes/admin/nav.php, sugar-event-calendar/includes/post/query-filters.php, sugar-event-calendar/includes/post/relationship.php, sugar-event-calendar/includes/post/taxonomies.php, sugar-event-calendar/includes/themes/legacy/ajax.php, sugar-event-calendar/includes/themes/legacy/calendar.php, sugar-event-calendar/includes/themes/legacy/event-display.php, sugar-event-calendar/includes/themes/legacy/events-list.php, sugar-event-calendar/includes/themes/legacy/functions.php, sugar-event-calendar/includes/themes/legacy/scripts.php, sugar-event-calendar/includes/themes/legacy/widgets.php
This commit introduces two new functions (sugar_calendar_get_requested_terms() and sugar_calendar_get_object_taxonomies()) and uses them to eliminate some hardcoded assumptions about the Calendar taxonomy, mostly that it is the only one.
We replace calls to get_object_taxonomies() with the new Sugar Calendar equivalent, thus allowing for all taxonomies for all post types that support "events" to get equal treatment.
See #96
=> Issue/96 - Taxonomies: add support for multiples.

sugar-event-calendar/includes/admin/meta-boxes.php, sugar-event-calendar/includes/common/time.php
This PR introduces the `sugar_calendar_get_clock_type()` function and uses it to decide how to handle the hour fields in the meta-box.
=> Issue/64 - Allow entering hours in 12 or 24 hour clock format.

sugar-event-calendar/includes/classes/database/engine/class-table.php
Prevents fatal errors in legacy PHP versions.
Fixes #105.
=> Issue/105 - Database: Shim clone() method.

sugar-calendar/includes/admin/hooks.php, sugar-calendar/includes/admin/meta-boxes.php, sugar-calendar/includes/admin/settings.php, sugar-calendar/includes/common/editor.php, sugar-calendar/includes/languages/sugar-calendar.pot
This commit adds a new setting to toggle Custom Fields on or off. This conveniently works for both Block and Classic editor types.
See #71.
=> Issue/71 - Editor: Add "Custom Fields" setting

sugar-calendar/includes/themes/legacy/events-list.php
This commit makes past/upcoming Events Lists split by "now" instead of the entire day of today.
It also swaps out "start_query" for "end_query", so that unfinished Events appear in upcoming while they are still happening, fixing a weird bug that could happen where an Event happening "now" could be ommitted from both past & upcoming lists.
See #44.
=> Widgets: Use request time instead of current day

sugar-calendar/includes/events/functions.php
This commit makes sure that sugar_calendar_get_event() accepts int/string/object/array types.
It also fixes some surrounding phpdocs.
Fixes #121.
=> Issue/121 - Events: Use Event_Query() inside sugar_calendar_get_event()

sugar-calendar/includes/admin/list-tables/class-wp-list-table-base.php, sugar-calendar/includes/admin/list-tables/class-wp-list-table-list.php
This commit adds support for a second "year" boundary in admin-area list-mode list-tables, allowing for showing more than a single year's worth of Events.
It also adds a little bit of magic to invert the view start & end, in the event that they are unintentionally impossible to compute.
Fixes #129.
=> Issue/129 - Add "start_year" list-table attribute.

sugar-calendar/includes/themes/legacy/ajax.php, sugar-calendar/includes/themes/legacy/calendar.php, sugar-calendar/includes/themes/legacy/functions.php, sugar-calendar/includes/themes/legacy/shortcodes.php
This commit introduces two helper functions to allow for correctly calculating the offset of shortcode output for all supported views (excluding "day" and "4day").
It also adds support for a "sow" shortcode attribute, allowing for start-of-week to be overridden on a per-shortcode basis, including AJAX navigation. This requires adding a new parameter to mulitple functions, so that it may be passed and/or overridden.
While poking around the shortcode attributes, I'm also adding support for "month" and "year" overrides, which oddly has never been supported but was easily added in. Shh. Maybe no one will notice! 🤫
Fixes #154
=> Issue/154 - Shortcodes: add support for all start-of-week values.

readme.txt
This change removes mention of the legacy "category" taxonomy, replacing it with the updated "Calendar" verbiage.
=> Issue/163 - Readme: remove "category" mentions with "calendar"

sugar-calendar/includes/admin/list-tables/class-wp-list-table-list.php
This change reduces some confusion for Lite users who were being presented a list-table column that did not have any functional purpose for their version.
It does this by checking the `sugar_calendar_get_recurring_date_query_args` filter. If there are no filters there is no recurring, so there is no need to show the column.
=> Issue/164 - Admin List Table: hide "Repeat" column if no query args exist.

package.json, sugar-calendar/includes/admin/list-tables/class-wp-list-table-base.php, sugar-calendar/includes/languages/sugar-calendar.pot, sugar-calendar/includes/themes/legacy/calendar.php, sugar-calendar/includes/themes/legacy/functions.php
This commit prevents "next month" type links & actions from skipping months when the next/prev month is shorter than the current one. It includes changes to both the admin and theme side calendars.
Fixes #168
=> Issue/168 - Next/Prev/Pagination: Avoid undesirable overflows.

sugar-calendar/includes/admin/list-tables/class-wp-list-table-base.php, sugar-calendar/includes/languages/sugar-calendar.pot
This method encapsulates the logic necessary to internally support WordPress filters on row-actions of various object types (post, comment, user...)
=> Issue/176 - List Tables: introduce filter_pointer_links() method

sugar-calendar/includes/themes/legacy/functions.php
This commit replaces the end time of "00:00:00" with "23:59:59", ensuring that Events for that day are included in the results.
Fixes a regression introduced in 7c7a0f9a9d1a41e28062b34f1f9c67cc476e5fb0.
=> Issue/182: Calendar: include the entire end day in Events query

sugar-calendar/includes/admin/meta-boxes.php
This commit improves the way that Calendars are queried when editing an Event via WordPress Admin, and ensures that selected calendars are checked with-or-without defaults.
=> Issue/193 - Calendars: unbreak Sugar_Calendar\Admin\Editor\Meta\calendars

sugar-calendar/includes/admin/nav.php
This commit fixes a bug that was causing WordPress core JavaScript to show an extra admin-notice.
Fixes #206.
=> Issue/206 - Nav: remove duplicated "wp-header-end" HR element.

sugar-calendar/includes/themes/legacy/functions.php
Changed the character that separates a range of dates from a hyphen to an en dash. Fixes #208
=> Separate date ranges with an en dash.

sugar-calendar/includes/languages/sugar-calendar.pot, sugar-calendar/includes/post/taxonomies.php
This commit ensures that the "Calendars" taxonomy appears as intended.
Fixes #127.
=> Issue/127 - Taxonomies: Show in REST when using Block Editor.

sugar-calendar/includes/classes/objects/class-date-recur.php
This change ensures that the Recur class does not error when an Event duration time is unknown, or has no defined end time. In this instance, when the start equals the end, a 0 value duration_time is set. Previous logic would discard this Event as erroneous, which was itself erroneous.
See #214.
=> Recur: support Events with "no known end".

sugar-calendar/includes/admin/list-tables/class-wp-list-table-base.php, sugar-calendar/includes/admin/list-tables/class-wp-list-table-day.php, sugar-calendar/includes/admin/list-tables/class-wp-list-table-list.php, sugar-calendar/includes/admin/list-tables/class-wp-list-table-month.php, sugar-calendar/includes/admin/list-tables/class-wp-list-table-week.php, sugar-calendar/includes/languages/sugar-calendar.pot
This method leans on strtotime() internally to get the week number for "this Thursday" which is used by the ISO-8601 standard to define the week of the year.
This change is necessary to ensure that the proper week number is output to the user in admin-area calendar views.
Fixes #218.
=> Issue/218 - Admin: Introduce Base_List_Table::get_week_for_timestamp().

sugar-calendar/includes/languages/sugar-calendar.pot, sugar-calendar/includes/themes/legacy/calendar.php, sugar-calendar/includes/themes/legacy/css/sc-events.css, sugar-calendar/includes/themes/legacy/functions.php
This change swaps out colors for RGBA, allowing output to work with both light & dark themes.
It also rearranges some HTML elements to make them easier to style and degrade gracefully when themes do weird things. Specifically, it moves the H2 ahead of the form & pagination, allowing it to hover above both while also giving all inputs more room to work with.
Several related improvements are being made to calendar styling at the same time, specific to links, fonts, padding, margin, and hovers, allowing for Sugar Calendar to be a bit more strict about its output without worrying about themes overloading it unintentionally.
=> Issue/221 - Legacy: styling improvements for all Default themes.

sugar-calendar/includes/themes/legacy/events-list.php, sugar-calendar/sugar-calendar.php
=> Issue/227 - Add widgets.php to Legacy loader

sugar-calendar/includes/themes/legacy/events-list.php
This commit fixes a notice (and warning) in some newer versions of PHP.
Props @joelyoder. Fixes #230.
=> Issue/230 - Legacy: swap the parameter order in an implode() usage.

sugar-calendar/includes/admin/upgrades.php
This commit ensures that these meta values are converted exactly as they were entered originally.
Fixes #231.
=> Issue/231 - Upgrade: do not use sanitization functions on start/end values.
